### ISSUE TITLE
OBS: change manually db-noobaa-db-pg-0 PVC from 50Gi to 200Gi

### ISSUE THREAD

**Issue by schwesig** [OCP-on-NERC/apps#431]
following a known issue, this needed to be adjusted manually,
following the approach and solution in the infra cluster

- https://github.com/nerc-project/operations/issues/131

- changes _on Monday, April 15, 2024 around 11:30am ET_

  - obs.nerc.mghpcc.org
    - Project: openshift-storage
    - [PersistentVolumeClaims](https://console-openshift-console.apps.obs.nerc.mghpcc.org/k8s/ns/openshift-storage/persistentvolumeclaims)
    - db-noobaa-db-pg-0

```
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
     storage: 50Gi
```
to
```
      storage: 200Gi
```

**Comment by schwesig** [comment]
done
```
status:
  phase: Bound
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 200Gi
```
